apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default

  destination:
    namespace: n8n
    server: https://kubernetes.default.svc

  source:
    repoURL: https:/charts.n8n.io
    chart: n8n
    targetRevision: 9.3.2

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
