apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  destination:
    namespace: n8n
    server: https://kubernetes.default.svc
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: n8n
    targetRevision: 1.16.28

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
