# ArgoCD App of Apps configuration
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-ai-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rbizzell40/devops-ai-stack
    targetRevision: HEAD
    path: applocations
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
